#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    links:
       - redis:redis
    expose:
       - 8000
    user: "1001:1002" #System dependent 
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000
  
  redis:
    image: redis
    expose:
      - 6379
  
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    links:
      - web:web
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      # - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

