#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    links:
       - redis:redis
    expose:
       - 8000
    user: "1001:1002" #System dependent
    environment:
        - GOOGLE_APPLICATION_CREDENTIALS=/code/mysite/CINS465-Primary-7a12f033f420.json
    working_dir: /code/mysite
    command: daphne -b 0.0.0.0 -p 8000 mysite.asgi:application
    # command: python /code/mysite/manage.py runserver 0.0.0.0:8000

  
  redis:
    image: redis
    expose:
      - 6379
  
  nginx:
    restart: always
    build: ./nginx/
    # volumes:
    #   - ./mysite/myapp/static:/static/
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    links:
      - web:web
